# action.yml
name: 'Batch Schema Publisher'
description: 'Publish your schemas to the Batch platform'
inputs:
  schema_id:
    description: 'Batch schema ID'
    required: true

  schema_type:
    description: 'Type of schemas we are working with'
    required: true
    default: 'protobuf'

  schema_name:
    description: 'Naming format to use for newly published schemas'
    required: true

  api_token:
    description: 'Batch API token'
    required: true

  root_dir:
    description: 'Directory that contains schemas and should be treated as root'
    required: true
    default: './'

  api_address:
    description: 'HTTP address for the Batch API'
    required: false
    default: 'https://api.batch.sh'

  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STREAMDAL_SCHEMA_ID: ${{ inputs.schema_id }}
    STREAMDAL_SCHEMA_TYPE: ${{ inputs.schema_type }}
    STREAMDAL_SCHEMA_NAME: ${{ inputs.schema_name }}
    STREAMDAL_API_TOKEN: ${{ inputs.api_token }}
    STREAMDAL_INPUT: ${{ inputs.input }}
    STREAMDAL_INPUT_TYPE: ${{ inputs.input_type }}
    STREAMDAL_API_ADDRESS: ${{ inputs.api_address }}
    STREAMDAL_OUTPUT: ${{ inputs.output }}
    DEBUG: ${{ inputs.debug }}
